#
# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
name: generic-runner
version: "1.0.7"
appVersion: "1.0.0"
description: generic-runner
type: application
home: https://github.com/TIBCOSoftware/tp-helm-charts
maintainers:
  - name: TIBCO Cloud Dev Team
    email: cloud@tibco.com
