#
# Copyright Â© 2024. Cloud Software Group, Inc.
# This file is subject to the license terms contained
# in the license file that is distributed with this file.
#

apiVersion: v2
name: provisioner-config-local
description: Platform Provisioner local config
type: application
version: "1.7.8"
appVersion: "2.0.1"
home: https://github.com/TIBCOSoftware/tp-helm-charts
maintainers:
  - name: TIBCO Cloud Dev Team
    email: cloud@tibco.com
